### ISSUE TITLE
100% CPU on Idle System

### ISSUE THREAD

**Issue by vogeljd** [cdapio/netty-http#76] opened 2019-09-06 21:17 UTC
Under heavy load I can relatively reproduce an issue where an executor thread will spin indefinitely using all available CPU.  

The issue can regularly be reproduced in under an hour.

I am using netty-http v1.2 with netty 4.1.39.  I've reproduced this issue with relatively current builds of java 8 and java 11, as well as a couple of recent builds of netty.  The process is running in docker on top of ubuntu 16.0.4.

Here are two stack traces, taken ~ 8 seconds apart on a system that is essentially idle.

The stack traces always show a call to peek on the queue that corresponds with one core being completely consumed.  If three cores are consumed while idle, I will see three calls to peek() in the stack-trace.

Here are two partial stack traces, taken a few seconds apart --

First trace excerpt

"crypto_https-executor-3725555" #4054640 daemon prio=5 os_prio=0 cpu=477643775.52ms elapsed=486250.22s tid=0x00007f41b002a800 nid=0x1f06 runnable  [0x00007f4026deb000]
   java.lang.Thread.State: RUNNABLE
        at io.netty.util.internal.shaded.org.jctools.queues.BaseMpscLinkedArrayQueue.peek(BaseMpscLinkedArrayQueue.java:379)
        at io.cdap.http.internal.NonStickyEventExecutorGroup$NonStickyOrderedEventExecutor.run(NonStickyEventExecutorGroup.java:286)
        at io.netty.util.concurrent.UnorderedThreadPoolEventExecutor$NonNotifyRunnable.run(UnorderedThreadPoolEventExecutor.java:277)
        at java.util.concurrent.Executors$RunnableAdapter.call(java.base@11.0.2/Executors.java:515)
        at java.util.concurrent.FutureTask.run(java.base@11.0.2/FutureTask.java:264)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(java.base@11.0.2/ScheduledThreadPoolExecutor.java:304)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.2/ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.2/ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(java.base@11.0.2/Thread.java:834)

"crypto_https-executor-3758018" #4093247 daemon prio=5 os_prio=0 cpu=469146975.74ms elapsed=477713.05s tid=0x00007f4110019800 nid=0x3767 runnable  [0x00007f40272f0000]
   java.lang.Thread.State: RUNNABLE
        at io.netty.util.internal.shaded.org.jctools.queues.BaseMpscLinkedArrayQueue.peek(BaseMpscLinkedArrayQueue.java:379)
        at io.cdap.http.internal.NonStickyEventExecutorGroup$NonStickyOrderedEventExecutor.run(NonStickyEventExecutorGroup.java:286)
        at io.netty.util.concurrent.UnorderedThreadPoolEventExecutor$NonNotifyRunnable.run(UnorderedThreadPoolEventExecutor.java:277)
        at java.util.concurrent.Executors$RunnableAdapter.call(java.base@11.0.2/Executors.java:515)
        at java.util.concurrent.FutureTask.run(java.base@11.0.2/FutureTask.java:264)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(java.base@11.0.2/ScheduledThreadPoolExecutor.java:304)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.2/ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.2/ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(java.base@11.0.2/Thread.java:834)

Eight Seconds Later

"crypto_https-executor-3725555" #4054640 daemon prio=5 os_prio=0 cpu=477650894.67ms elapsed=486258.15s tid=0x00007f41b002a800 nid=0x1f06 runnable  [0x00007f4026deb000]
   java.lang.Thread.State: RUNNABLE
        at io.netty.util.internal.shaded.org.jctools.queues.BaseMpscLinkedArrayQueue.peek(BaseMpscLinkedArrayQueue.java:379)
        at io.cdap.http.internal.NonStickyEventExecutorGroup$NonStickyOrderedEventExecutor.run(NonStickyEventExecutorGroup.java:286)
        at io.netty.util.concurrent.UnorderedThreadPoolEventExecutor$NonNotifyRunnable.run(UnorderedThreadPoolEventExecutor.java:277)
        at java.util.concurrent.Executors$RunnableAdapter.call(java.base@11.0.2/Executors.java:515)
        at java.util.concurrent.FutureTask.run(java.base@11.0.2/FutureTask.java:264)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(java.base@11.0.2/ScheduledThreadPoolExecutor.java:304)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.2/ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.2/ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(java.base@11.0.2/Thread.java:834)

"crypto_https-executor-3758018" #4093247 daemon prio=5 os_prio=0 cpu=469153397.03ms elapsed=477720.98s tid=0x00007f4110019800 nid=0x3767 runnable  [0x00007f40272f0000]
   java.lang.Thread.State: RUNNABLE
        at io.netty.util.internal.shaded.org.jctools.queues.BaseMpscLinkedArrayQueue.peek(BaseMpscLinkedArrayQueue.java:379)
        at io.cdap.http.internal.NonStickyEventExecutorGroup$NonStickyOrderedEventExecutor.run(NonStickyEventExecutorGroup.java:286)
        at io.netty.util.concurrent.UnorderedThreadPoolEventExecutor$NonNotifyRunnable.run(UnorderedThreadPoolEventExecutor.java:277)
        at java.util.concurrent.Executors$RunnableAdapter.call(java.base@11.0.2/Executors.java:515)
        at java.util.concurrent.FutureTask.run(java.base@11.0.2/FutureTask.java:264)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(java.base@11.0.2/ScheduledThreadPoolExecutor.java:304)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.2/ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.2/ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(java.base@11.0.2/Thread.java:834)

**Comment by chtyim** [comment] 2019-09-06 23:31
Do you observes this when the server is under high load or is it idle?? If it is under high load, how high the load is?

**Comment by vogeljd** [comment] 2019-09-07 00:10
It gets into the state under high load.  Once a thread gets into the bad state it will consume 100% of cpu on one core until the process exits.  

Once a the threads goes bad I remove all load from the service and it continues to peg one core until I kill the process.    

What’s harsh is that I’ve seen 8 threads get into this state at once, so 8 core were pegged. 

I can reproduce it by having a few client threads calling a very lightweight api in a tight loop. 

Jim
.

**Comment by chtyim** [comment] 2019-09-07 00:11
An I assume all your clients are making synchronous calls, meaning it wait for the server to respond before making another call, right?

**Comment by vogeljd** [comment] 2019-09-07 00:27
Correct

**Comment by chtyim** [comment] 2019-09-13 22:51
We are able to reproduce the issue and it is caused by a bug in the NonStickyEventExecutorGroup that comes from the netty library. The bug causes a consumer thread spinning forever if the race condition happen.

**Comment by vogeljd** [comment] 2019-09-16 14:07
Is it possible that there is more than one thread on the consumption side
of that multi-producer/single consumer queue.  After I put a lock around
the two consumption methods on that queue, I can no longer reproduce the
problem.

**Comment by chtyim** [comment] 2019-12-03 08:30
Fixed by PR #77

**Closed as completed by chtyim** 2019-12-03 08:30 UTC
